### ISSUE TITLE
documentation: clarify python dependency requirement

### ISSUE THREAD

**Issue by pablomalo** [d-enk/ulauncher-case-converter#1]
Not being familiar with python, I had some trouble getting the extension to work as pip3 could not find the `caseconverter` package. Turns out I needed to run `pip3 install case-converter` (with a hyphen).

Maybe this is worth mentioning in the README ? 

Very happy otherwise. Thanks for this extension!

**Comment by d-enk** [comment]
Thanks for your comment!

I don't often work with python myself too.
So I just accidentally used the name of the library from the import and didn't check it...
